[package]
name = "tabulon"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "tabulon_macros",
]

[[bench]]
name = "eval-bench"
harness = false


[dependencies]
cranelift = "0.124.1"
cranelift-jit = "0.124.1"
cranelift-module = "0.124.1"
cranelift-native = "0.124.1"
thiserror = "2.0.17"
inventory = "0.3"
tabulon_macros = { path = "tabulon_macros" }
uuid = { version = "1.18.1", features = ["v4"] }

[dev-dependencies]
fasteval = "0.2.4"
criterion = "0.7.0"
rand = "0.8"
foldhash = "0.2.0"
libc = "0.2"

[features]
default = ["optimize"]
optimize = []